### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by jdabs** [digibyte/playground.digibyte.io#1]
I'm getting a javascript error on Chrome 62 on Windows 7 and on ChromeOS. It looks like it could also be causing image assets not to load. You can see that images are showing as blank squares. 

To see the error:
1. Go to playground.digibyte.io
2. open your inspector console
3. reload the page
4. It will show as a console error

Screenshot attached is the error I see.
![screenshot 2017-11-25 at 1 10 02 pm](https://user-images.githubusercontent.com/6774432/33233336-c6858856-d1e2-11e7-8936-ef81c635f4b4.png)

**Comment by digicontributer** [comment]
Thanks for letting us know. Should be fixed but may require you to ctrl + f5
